apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  values:
    installNoConntrackIptablesRules: true
    bpf:
      masquerade: true
      hostLegacyRouting: true
    cni:
      exclusive: true
    nodePort:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    localRedirectPolicy: false
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false
    k8sServiceHost: localhost
    k8sServicePort: 7445
    routingMode: native
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    l2announcements:
      enabled: true
      leaseDuration: 15s
      leaseRenewDeadline: 5s
      leaseRetryPeriod: 2s
    loadBalancer:
      mode: dsr
      algorithm: maglev
      acceleration: best-effort
      serviceTopology: true
    envoy:
      enabled: false
