apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
  hostnames:
    - grafana.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: vmks-grafana
          port: 80
