---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal-daemonset
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 192.168.100.15
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: internal-daemonset
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.${cluster_subdomain}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.${cluster_subdomain}"
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-ingress-tls-secret
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
