---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 1m
  path: ./crds/dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
