  apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: n8n-db
  spec:
    imageName: ghcr.io/cloudnative-pg/postgresql:17.2
    monitoring:
      enablePodMonitor: true
    instances: 1
    bootstrap:
      initdb:
        database: n8n
    postgresql:
      parameters:
        shared_buffers: "64MB"
    resources:
      requests:
        memory: "512Mi"
      limits:
        memory: "512Mi"
    storage:
      size: 1Gi
      storageClass: standard
