apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: homelab
spec:
  template:
    spec:
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
