creation_rules:
  # Prod secrets
  - path_regex: .*prod/.*values-secret.yaml
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*prod/.*secret.json
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*prod/.*secret.env
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*prod/.*.yaml
    encrypted_regex: ^(data|stringData|value)$
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  # Dev secrets
  - path_regex: .*dev/.*values-secret.yaml
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
  - path_regex: .*dev/.*secret.env
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
  - path_regex: .*dev/.*.yaml
    encrypted_regex: ^(data|stringData|value)$
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
