creation_rules:
  # Homekube secrets
  - path_regex: .*homekube/.*values-secret.yaml
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*homekube/.*secret.json
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*homekube/.*secret.env
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  - path_regex: .*homekube/.*.yaml
    encrypted_regex: ^(data|stringData|value)$
    age: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
  # Local secrets
  - path_regex: .*local/.*values-secret.yaml
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
  - path_regex: .*local/.*secret.env
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
  - path_regex: .*local/.*.yaml
    encrypted_regex: ^(data|stringData|value)$
    age: age12fr7rv0m09slmt906xzpyh7e3aqw0es82yzvt0m8tzuv5dzj7vcsc9vvln
