---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      version: "0.20.x"
  values:
    serviceMonitor:
      enabled: true
    bitwarden-sdk-server:
      enabled: false
