apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
spec:
  chart:
    spec:
      version: "4.12.x"
  values:
    storageClass:
      create: true
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      name: nfs-csi
      parameters:
        server: 192.168.100.3
        share: /data
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.1
    externalSnapshotter:
      customResourceDefinitions:
        enabled: false
