apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: homelab
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: homelab
  interval: 5m
  install:
    remediation:
      retries: 3