---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: crds
  retryInterval: 1m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/prod
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      env: "prod"
      cluster_name: "talos_homelab"
      cluster_subdomain: "talos.sleepfox.ru"
