---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-operator-crds
spec:
  interval: 24h
  chart:
    spec:
      chart: piraeus
      version: "2.10.5"
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 0
    rbac:
      create: false
    serviceAccount:
      create: false
    podDisruptionBudget:
      enabled: false
    tls:
      autogenerate: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              $patch: delete
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: unused
          - target:
              kind: ValidatingWebhookConfiguration
            patch: |
              $patch: delete
              apiVersion: admissionregistration.k8s.io/v1
              kind: ValidatingWebhookConfiguration
              metadata:
                name: unused
          - target:
              kind: Service
            patch: |
              $patch: delete
              apiVersion: v1
              kind: Service
              metadata:
                name: unused
          - target:
              kind: ConfigMap
            patch: |
              $patch: delete
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: unused
