apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jira
  namespace: homelab
spec:
  releaseName: jira
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: jira
      sourceRef:
        kind: HelmRepository
        name: atlassian-data-center
        namespace: homelab
