apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  chart:
    spec:
      version: "11.x.x"
  dependsOn:
    - name: "vmks"
      namespace: "monitoring"
  values:
    image:
      tag: v0.28.0 # {"$imagepolicy": "flux-system:blackbox-exporter:tag"}
    serviceMonitor:
      selfMonitor:
        enabled: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
            tls_config:
              insecure_skip_verify: true
