---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost
  namespace: homelab
spec:
  chart:
    spec:
      chart: mattermost-team-edition
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: mattermost
  interval: 50m
  install:
    remediation:
      retries: 3
