---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: apps-n8
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden
    kind: ClusterSecretStore
  target:
    name: n8n
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: REDACTED
        property: N8N_ENCRYPTION_KEY
    - secretKey: GIGACHAT_CREDENTIALS
      remoteRef:
        key: REDACTED
        property: GIGACHAT_CREDENTIALS
