apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: arc-github-token
    namespace: arc-runners
    labels:
        app.kubernetes.io/name: arc-github-token
        app.kubernetes.io/instance: infra-arc-controller-gh-token
        app.kubernetes.io/managed-by: kustomize
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: vaultwarden
        kind: ClusterSecretStore
    target:
        name: pre-defined-secret
    data:
        - secretKey: ENC[AES256_GCM,data:xMBg7FuecCntD1tc,iv:t4xkjzPQpAQ837DZIF6iuRCQk5kta/FGXC5MizbgaGA=,tag:jGmIdevGS1CvWR6KoiGl8w==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:cU0fwXmLeDYORMb2wBQmVCVDzeZ1mvsleTVKoPdleu3cN0IQ,iv:bg35LwdAgloVtrmAnBjVCbJ6NYJbvB0YRhfIhcSj0iY=,tag:rIaDv6wLxyQGADDWYfRjNg==,type:str]
            property: ENC[AES256_GCM,data:bIWja4y6MRoeUQmo,iv:NsfuUwevuN10lwIWUhi+OHT7OIAyk000YOxNxFRyjIw=,tag:bZb3/8a6fp8Xbv9RzdscdQ==,type:str]
sops:
    age:
        - recipient: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeG85VFJ2R0JSR3VUM3d1
            VEwrV0VkWTVpSG0yRlJWaTlib1Q2enkreFNBCnBnQWVLQndiclFTYVBNcm9Ta2Vq
            VVl3VkQyQU4ydTJqQXRZeElFMlBuc3cKLS0tIGNxWkVqRzBoNGR0cXNtQk9NdWRS
            UlYzWTNBb21LREppWEc2MUQ4UHlVM2cKrsrAeW3WTZnvv4J65bqE0mQePvP7N2AA
            uGqhyXN/sSXrJ0QLy+oRal1BBONBTafJPMIR26pRhvijaUouVG/YKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T13:26:29Z"
    mac: ENC[AES256_GCM,data:bKauqrZXpkOPmWSz7w3k7Fii74nWRNNRCF0X7QrToTiYABz8Qofu6w166h4tbE2y+aNciCygo9MHLvTJeJEZI/ut3w0EQPx3xt+uHVht11vfKUBT7eGoVLPKQFYlpCFir6+QWWxZhz0FYAJzDOlYeUn+bhseJ2Tm1fGaUM3De7o=,iv:q2twoifXW7SHGUKPLZJwf48aAZeslCfttGilZWIS8bA=,tag:2l4AAWm21riX3O6Df/FiJw==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
