apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
  labels:
    app.kubernetes.io/name: arc-github-token
    app.kubernetes.io/instance: infra-arc-controller-gh-token
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden
    kind: ClusterSecretStore
  target:
    name: pre-defined-secret
  data:
    - secretKey: github_token
      remoteRef:
        key: 68948f48-b6e7-420e-90fa-2adbeccf0b4a
        property: github_token
