apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:lRo2L/SxEaLwHS2vMom8mH4c2sypsBDz9igZpUCdArs+,iv:sdirQqLWuPQFweJtfBgKQ4jioHFkYV85vaXiZqci6Ms=,tag:ri1LV3/IMDGjV67FnZadJg==,type:str]
    email: ENC[AES256_GCM,data:WTdn2CfRiU4TyakLG7+MkbSCBGPJv1vyy1dzLck=,iv:atNj3nxk4I5arYbwP226mottOsuZGmplO36SucJJ5RI=,tag:i4z98Xq10eYLGyoJaUY5Kg==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWHlyb3drY2M0MnYyT3V4
            UGQ4WFBEOHFoYkw0MXl2SlBXS0V2UnY0eTFzCjJ4OXgzNE9ueFRQekhiY1ZtZUFj
            SlBKVzBVMjl5L0FBRE1wY21qMi9WZncKLS0tIG5RUE9KeFdzd0dhM2VOeFNpMmgw
            QUpqNnlOb2ova3VManNWcHNPN2FrSU0KTfqcEw8sC3QB2SIqSBMXLPPw1u7TuyW6
            YwZ4Rm4NC1FAlw5OZpXGQ891aEVavLG/T7QhAFIgXCmScc9yCcxFWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T17:56:59Z"
    mac: ENC[AES256_GCM,data:9qXlzEVoLfWjpKZR17eAvG2ZNYUOd+0AUpKgmDL5FItIQudToG/RSRD65KuOVE0QM8DrNg4FnjNscD2ynxpOw7BiVws5XKCK9Xf/udTAXbdlbA5lGsXtPSbDX2/sBFt4kWIdyMZAP6K1MrtSsTuKWz1byNZIY2TSAJ4r+7b+vBA=,iv:kIPqAYGIcXTAlXQmcp7VyBE31d3nEjzXpvd11RJE3a8=,tag:gwGI8SO5yso9JCg1btFSFQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
