apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:0XP6sUNULsPmi/30UltTCh+oFVQi0ulYSDw2xloE+vJub3Y6gbVcxQ==,iv:IVRhopak6DhlEWw6pJmAUyE+ude6Mm8W0q5bgqbZK84=,tag:J3l3CfNU9vhdJU7qCrfPXw==,type:str]
    email: ENC[AES256_GCM,data:KtTz1Gv1SGsNBHBLjU/sZUaxIyee4roOBAVDZlQ=,iv:MW/3b+PK2G9J9LGwZVJFfztkkPcSHL6EtMwcos9b7dw=,tag:5+9ZJbokThIA9M8NTfduzA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWHlyb3drY2M0MnYyT3V4
            UGQ4WFBEOHFoYkw0MXl2SlBXS0V2UnY0eTFzCjJ4OXgzNE9ueFRQekhiY1ZtZUFj
            SlBKVzBVMjl5L0FBRE1wY21qMi9WZncKLS0tIG5RUE9KeFdzd0dhM2VOeFNpMmgw
            QUpqNnlOb2ova3VManNWcHNPN2FrSU0KTfqcEw8sC3QB2SIqSBMXLPPw1u7TuyW6
            YwZ4Rm4NC1FAlw5OZpXGQ891aEVavLG/T7QhAFIgXCmScc9yCcxFWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:20:02Z"
    mac: ENC[AES256_GCM,data:iQQqKnlqrORrdF5FPDf3cxP/xxVJ9Y8vw+KyACZWvxsOaebdSiD/593l6o6v0zCjAmRwCWHHO0tONleniP9hiclnW8+6NDmUTEoCy+7KvGbwQz69YcdypwBEfFYbUKWtK9cVFPi31qVN7CVnwVJNI4Rl0VLXs3XOvO754h2FKWM=,iv:X06BYfmgNCvV3q+W71xwa2fHIsmyY+LXXQnqLyPv9cg=,tag:cu9yrBdFcdEfftk4BMrEtw==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
