apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:EIAqGc/HlkBK2P7F8m/aFzQLTXh9cHeeiUcDqIGuvwZwv3MHNelF0/7WzfouTTViyVZjLv3MKVQ=,iv:+U6BcHJgThYo+oE4wcw0LW5K99yEWPBGvhGX10abnBw=,tag:hQAGV5LB7dv/rwScbOzVcQ==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRFZTQmkxRkY2NHM4dkxo
            WEVtWFQyaTJwbXpIdUdVWGRkL3RpK2lpZ24wCnNUNmxYOHQwdHpyaXJDcWFVOTVN
            R2F1aVhqcDFYWWVJT0lKMHFtejVRbG8KLS0tIGgvdkZpMUdFamFXVDFMTkQ5V2Vu
            K2d3aFUyTExsc3hpT0hOQ0pId1VLWlUKsD24oEydBQzPHoVASgwsZ+bH6UwYoEGz
            CctCqZBPWrfqfGb7X3YqrD1MNF/avb3QDm/WtEp3KmQsOSXOWytTAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T18:35:30Z"
    mac: ENC[AES256_GCM,data:U9bTnxoVza91IH5PGjt9OXJ4oQajO4aQtpcLYBnWRheqBsHXfzq+YT4WnA4K2LVC2CxYkTIFcmtrSNkSJn4nsNcA/z6o+vvtOIx3A4B42mgFR2U7N08ajiK9eARFPZQYZZnHyRpkz6+nYmoYOFoSARmmfn11FYeBRy1h0nA9ISM=,iv:Qsp7jpVnmuPW31vrj+S9LbPGSpw64WKpK4k2eDqw1ZA=,tag:6SiQ4X0DnpA7iTRIaXEeEQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
