---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: immich
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: immich
  egress:
    # check release updates
    - toFQDNs:
        - matchName: api.github.com
        - matchName: huggingface.co
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
