apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
spec:
  parentRefs:
    - name: external
      namespace: envoy-gateway-system
    - name: internal
      namespace: envoy-gateway-system
  hostnames:
    - vaultwarden.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: vaultwarden
          port: 80
