---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator-crds
spec:
  interval: 24h
  chart:
    spec:
      chart: victoria-metrics-operator-crds
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: vm
