apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/bundles/stage-flex
  - cert-manager
  - envoy-gateway
  - flux-promotion
  - immich
  - jellyfin
  - linstor
  - n8n
  - open-webui
  - qbittorrent
  - vaultwarden
patches:
  - path: mattermost/rm-helm-release.yaml
  - path: mattermost/rm-helm-repo.yaml
  - path: cilium/helm-release.yaml
    target:
      kind: HelmRelease
      name: cilium
  - path: immich/immich-values.yaml
    target:
      kind: HelmRelease
      name: immich
  - path: linstor/helm-release.yaml
    target:
      kind: HelmRelease
      name: piraeus-operator
  - path: linstor/git-repos.yaml
    target:
      kind: GitRepository
      name: piraeus
  - path: n8n/n8n-values.yaml
    target:
      kind: HelmRelease
      name: n8n
  - path: qbittorrent/downloads-patch.yaml
    target:
      kind: Deployment
      name: qbittorrent
  - path: jellyfin/jellyfin-values.yaml
    target:
      kind: HelmRelease
      name: jellyfin
  - path: open-webui/open-webui-values.yaml
    target:
      kind: HelmRelease
      name: open-webui
  - path: vaultwarden/vaultwarden-values.yaml
    target:
      kind: HelmRelease
      name: vaultwarden
  - path: cert-manager/helm-release.yaml
    target:
      kind: HelmRelease
      name: cert-manager
