---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bundle
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 1m
  retryInterval: 1m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/apps
  prune: true
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      env: "staging"
      cluster_name: "talos_staging"
      cluster_subdomain: "staging.sleepfox.ru"
