apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ingress
spec:
  secretName: wildcard-ingress-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: "sleepfox.ru"
  dnsNames:
  - "sleepfox.ru"
  - "*.${cluster_subdomain}"
  - "${cluster_subdomain}"
