apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:pGE0fPi3bTjiymNK/q4YHBCTUqSnls+YqfEvlDj1TBbB2oTUG7hsdQ==,iv:hdNuPKr87z/W7Pi9Uw0Dm98TYTs5aqsueP1yuUqFW2I=,tag:E4mQ471ZmGEZS0lS4kJtbw==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR3FjdUlybUlUK1lnTTBL
            QXJUem96SWpIVlIxenBRb2M1enV1SGc0ckNjClhBaFJRbmZkMEpERXNVNk5UVUtt
            VmkzaU5qTkIvZW1wYzlkeDM1ZEUzdlUKLS0tIFliUElSSWVtNXFoaWthL0UrMk5m
            NVRKaThhUDJ4UUluYnNxRjNnMXZseGMKCj8NTirxDywApAkh63cXVvgpCMHtWn/u
            MMGMGAXqDrvL5lvO2zFF94BTZPjvKfIT/16FKApYT6mdX49kNnHngg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:02:47Z"
    mac: ENC[AES256_GCM,data:BOOhcNsyCUq9iwoj2lbDUCQYsujTs7m4j8EMC1afG5jtJu5tbveLvXnfo8z4p2l6FpvKvKTko0p9/30KOaYCFUK3jqc4w/Tef/Zs5ZZOtzJTk2t4nXbwHgIydi0mCEItz3NqGg4dpDRkotFw4aqyNJldcInmlueKzXDypANRxlA=,iv:73XKcd1z+BOrloOydjLhEja4Xq7urXzCudmouk+zXls=,tag:cy/d306k2Z99e988BgWzug==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
