apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      version: "1.19.x"
  values:
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=192.168.100.2:53
