apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  labels:
    app: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
  volumeMode: Filesystem
