apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/bundles/staging-flex
  - flux-promotion
  - linstor
patches:
  - path: mattermost/rm-helm-release.yaml
  - path: mattermost/rm-helm-repo.yaml
  - path: cilium/helm-release.yaml
    target:
      kind: HelmRelease
      name: cilium
  - path: linstor/helm-release.yaml
    target:
      kind: HelmRelease
      name: piraeus-operator
  - path: linstor/git-repos.yaml
    target:
      kind: GitRepository
      name: piraeus
