apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jira
  namespace: homelab
spec:
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
  hostnames:
    - jira.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: jira
          port: 80
