apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zeroclaw
  labels:
    app.kubernetes.io/name: zeroclaw
    app.kubernetes.io/instance: apps-zeroclaw
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden
    kind: ClusterSecretStore
  target:
    name: zeroclaw
  data:
    - secretKey: api-key
      remoteRef:
        key: 861f5786-2fb2-4842-8224-66e5405e3130
        property: ZEROCLAW_API_KEY
    - secretKey: telegram-bot-token
      remoteRef:
        key: 861f5786-2fb2-4842-8224-66e5405e3130
        property: TELEGRAM_BOT_TOKEN
    - secretKey: openai-api-key
      remoteRef:
        key: 861f5786-2fb2-4842-8224-66e5405e3130
        property: OPENAI_API_KEY
    - secretKey: https_proxy
      remoteRef:
        key: 861f5786-2fb2-4842-8224-66e5405e3130
        property: HTTPS_PROXY
