apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
  namespace: homelab
spec:
  parentRefs:
    - name: internal
      namespace: istio-ingress
  hostnames:
    - n8n.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: n8n
          port: 80
