apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - goldpinger-http-route.yaml
configMapGenerator:
  - name: goldpinger-dashboards
    namespace: monitoring
    files:
      - goldpinger-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: goldpinger
        app.kubernetes.io/component: goldpinger
        kustomize.toolkit.fluxcd.io/substitute: disabled
