apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 24h
  url: https://github.com/cloudnative-pg/cloudnative-pg.git
  ref:
    tag: v1.27.0
  ignore: |
    # exclude all
    /*
    # include crd dir
    !/config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  interval: 24h
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudnative-pg
