# See https://github.com/piraeusdatastore/piraeus-operator/tree/v2/charts/piraeus
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-operator
  namespace: linstor
spec:
  interval: 15m
  timeout: 1m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/piraeus
      sourceRef:
        kind: GitRepository
        name: piraeus
        namespace: linstor
  values:
    installCRDs: false
