apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:qOrM8mNe2HC89Os63ATj8UUPxULp5bNt/QsMlXtmMg1acO9GyPX+cJaCNbYKuF37yivsHDrw6uVHJkCJTBOTaRRhF4lNl1OFnPo686e3dtDGMY9FfkEpbCMc8J8Q,iv:MCQmi69hJGbQDXRixGUprC3OxGTHDTx5QFYToi5/RYs=,tag:ZREhiBaxg5a/+2YRe5mH5Q==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0w1OTE2TDI3aUEzbzJL
            VWdZN2lZS0ZESWcwMEVRY1VrVm9YWWRZcmhjCnprZ2dzQVowNzFrS3lnOUF2cGpO
            NG1Lc25LdllzMnNjNHpMa3l3YmJNSVEKLS0tIEM4VTVzTGNXdTBXUE1ZalJMeWdq
            Qm9aVTgxOTJzanNpMlRndWEwL0tBTzQKK81zOYytsGIS7IFSXQv4Ttl8YS3/6+s2
            cPZZ+jEKMLL9GiQ8d/i7a46P8bn+obge1faXMdReLtxIdGU3NxJlpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:43:22Z"
    mac: ENC[AES256_GCM,data:dOAm/Op+jaaFEqROAjXsrs+r2qAecM/xmNPDlAXhCBPJopLfrqdn6JFgtH912w3FiqZXR0yCjVzgXQfh2zBkHdQVZGmLsWCYR9i3Tnxy4zKdfEGncNRPXrGhAxZqv8w+UJ4cHJsxfAQYylu7NTAUXM5U+TCpBCaOk/bNZyUhNr8=,iv:CXYO8sfpPeNWzDYgjZ4K4OmSpxqlYtjsWXq3nPsTGYw=,tag:DDPR0As/mcbpJCAyRTQi6w==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.11.0
