apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: homelab
spec:
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
  hostnames:
    - jellyfin.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
