---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-media-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  volumeName: jellyfin-media-pv
  storageClassName: nfs-csi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local
