---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local
