apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  releaseName: envoy-gateway
  chartRef:
    kind: OCIRepository
    name: envoyproxy-gateway
    namespace: envoy-gateway-system
  interval: 15m
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
