---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv-nfs
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.100.3#data#immich#
    volumeAttributes:
      server: 192.168.100.3
      share: /data
      subdir: immich