apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
spec:
  parentRefs:
    - name: external
      namespace: envoy-gateway-system
    - name: internal
      namespace: envoy-gateway-system
  hostnames:
    - immich.${cluster_subdomain}
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
