apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: homelab
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: homelab
  interval: 50m
  install:
    remediation:
      retries: 3
