apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-cluster
  namespace: linstor
spec:
  values:
    linstorSatelliteConfigurations:
      - name: talos-loader-override
        podTemplate:
          spec:
            initContainers:
              - name: drbd-shutdown-guard
                $patch: delete
              - name: drbd-module-loader
                $patch: delete
            volumes:
              - name: run-systemd-system
                $patch: delete
              - name: run-drbd-shutdown-guard
                $patch: delete
              - name: systemd-bus-socket
                $patch: delete
              - name: lib-modules
                $patch: delete
              - name: usr-src
                $patch: delete
              - name: etc-lvm-backup
                hostPath:
                  path: /var/etc/lvm/backup
                  type: DirectoryOrCreate
              - name: etc-lvm-archive
                hostPath:
                  path: /var/etc/lvm/archive
                  type: DirectoryOrCreate
    storageClasses:
      - name: local
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        parameters:
          linstor.csi.linbit.com/storagePool: "data"
          linstor.csi.linbit.com/layerList: "storage"
          linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
        volumeBindingMode: WaitForFirstConsumer
