apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:35tktikVnuCVUXRQHYouYmxaQUIMLp4mDxu23AxuoZ/Kb/CdUSwYL7h3jXVmh0PV4HpGKqUKQvc=,iv:4KSFhByWupcuZdU5UgBvICdbnNvAafE42atRvtJp9RI=,tag:nZ6nwgxJWD1CRTRsGrijnA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcjJKS1B4WkR5WXFNVW9z
            bEJ2V0psS2xzSjJTQnZNYVJsVlBIL3hoWldVCjN6WHNUaFNrZThsVTBta0VDRDZ3
            bTMrTk9xU0tXenJxQ2p0ZW5oeHpMRFUKLS0tIGtpYXhqZWlTcktUMXRBUmNUeFNn
            dndYYXR3eWpiMjR2UGZxanNjZlF0NVUKi6roAhiHo71MO/SBvoc2Wfvqlq5WCmtn
            bJiRYVyeFQ+aCM8tDJ/RA7DxkXqP4bOGIg5HTmkdNkQS5PGqWKgPgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T05:08:22Z"
    mac: ENC[AES256_GCM,data:JRyGkK6e/hjmN4PppmU97lxNNwLCjlp6i7miaPr5GCKxTuDu2HMatsGoeug9xW/DsN5zm+wcKR1FNX+5Dp1r415p4L6c8Iz4VWPuLxgn9fWo9iH+HLs/Dpsubf9ikmHZwFNLMTa4nYn1TJy7bG50yhEC1MgHTD//K5KZPg/eTtM=,iv:TO3kALtmqn16SB4ICffEKwsoSq3JffSsm0+T8ef0Vbg=,tag:4AanAfIfriugznGUgX4O0w==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
