apiVersion: v1
kind: Secret
metadata:
    name: github-dispatch-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:xZzVcWzC637jnV7e847WGfv8xI2vlZ2wrSVLJ5/Qdx1zPmP8hw5/WgMwSTwwuCJSYO10UDfvFh9LSs1YXA1n43raqZbUmAzlQuVTwLynk8sUmSL2XyNtbYzWqN+S,iv:SiIqZwQHCO95QYKtT9uwWxoCL5zuxEGigXKCcAfHS9Y=,tag:TsFtwIUU4waYN7FKkc1jGA==,type:str]
sops:
    age:
        - recipient: age1mtp6p0xvwdf4v2q7fd3cmenkdlwmt3l2xuc5ltkf6lhe9r8lquyqzeehax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTEs2UStIemIxSkVuN1Bx
            Yy9DUVJpRHZNdjB5M2tISlliZ04rNlJHSEVBClJCbGpGb1AwaHJrRWM0MUozNjAv
            alNiYjN4eDRuNi9IQzZpL2ZmTFJwVXMKLS0tIEQ1a1dXaWdRQWdKWlAxYXFJdm9R
            czJCUXJpeU1xL3RYUVNJM2ZMTzlHOFUKgCJbm8VVp8HR00zAzpyghiEhpJoC7q9/
            QN/gwAZFAj7xiO+gQBnRTuh0QAiNaB2JlBRTPC/QJIqZppvhgHCFFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:02:47Z"
    mac: ENC[AES256_GCM,data:8r20QauQFJnlfIonZ4anyDQgXiYn3ajjjlb+S/OuOiqfrstoj6ZwGB3XzTKn5TuAt1jB8DBYr93pg/+Q/lrUrVC0jCNxWSdPP1iH6qEDZo3ItX7pZBVSEebzykw7vwyYEX3J8O4A3PgxIhgkyZCKybrPm3wtBKY7a1eBjnTWmoY=,iv:VD6G5oNYjCbo8noPedC4daS6Cd1AFXJfLXEFlWxAfMs=,tag:je23Ycw8eW0vjgffownOWQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.12.1
