---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vaultwarden
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden-cli.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.fields[?@.name==\"{{ .remoteRef.property }}\"].value"